Repository Arquisoft/wichat_es6c, pull requests merged in 2025-04, with the labels that each got.

#89 Mejorada la velocidad del juego
  arrancaTodo.bat
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  questionservice/services/question-generate-service.js
  questionservice/services/question-service.js
  webapp/src/pages/Game.js
Labels: back-development

#78 Cambios del front en la página de finalización del juego
  webapp/package-lock.json
  webapp/package.json
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
Labels: front-development

#91 Api documentation
  gatewayservice/gateway-service.js
  gatewayservice/openapi.yaml
  gatewayservice/openapiAntiguo.yml
  users/historyservice/history-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/NavBar.js
  webapp/src/pages/History.js
Labels: documentation, front-development, back-development

#110 Arreglado bug en el que se cargaban las preguntas varias veces
  questionservice/services/question-data-service.test.js
  questionservice/services/question-generate-service.test.js
  webapp/src/pages/Game.js
Labels: bug

#112 Añadidos tests para question service e history service
  questionservice/services/question-generate-service.js
  questionservice/services/question-generate-service.test.js
  questionservice/services/question-service.js
  questionservice/services/question-service.test.js
  users/historyservice/history-service.js
  users/historyservice/history-service.test.js
  users/historyservice/package.json
Labels: testing

#115 Añadido lo restante a la documentación.
  gatewayservice/openapi.yaml
  webapp/src/pages/History.js
Labels: documentation

#122 Fix bugs LLM, Docker y Apiendpoint
  docker-compose.yml
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  webapp/src/components/Chat.js
  webapp/src/pages/History.js
Labels: bug

#124 internacionalizacion
  gatewayservice/gateway-service.js
  questionservice/models/question-model.js
  questionservice/services/question-data-service.js
  questionservice/services/question-data-service.test.js
  questionservice/services/question-generate-service.js
  questionservice/services/question-generate-service.test.js
  questionservice/services/question-service.js
  questionservice/services/question-service.test.js
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
  webapp/package.json
  webapp/public/images/flags/spain.png
  webapp/public/images/flags/uk.png
  webapp/src/components/Chat.js
  webapp/src/components/NavBar.js
  webapp/src/index.js
  webapp/src/localize/en.json
  webapp/src/localize/es.json
  webapp/src/localize/i18n.js
  webapp/src/pages/Game-VS.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/GameType.js
  webapp/src/pages/History.js
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
  webapp/src/pages/UserHome.js
  webapp/src/tests/pages/Login.test.js
  webapp/src/tests/pages/Register.test.js
Labels: internationalization

#126 Añadidos test unitarios
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/package.json
  llmservice/llm-service.test.js
  llmservice/package.json
  questionservice/package.json
  questionservice/test/question-data-service.test.js
  questionservice/test/question-generate-service.test.js
  questionservice/test/question-service.test.js
  users/authservice/auth-service.test.js
  users/authservice/package.json
  users/userservice/package.json
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/tests/pages/Register.test.js
Labels: testing

#127 Mejora de código
  questionservice/services/question-generate-service.js
  questionservice/services/question-service.js
  questionservice/test/question-service.test.js
  questionservice/utils/queryCategories.json
  questionservice/utils/utils.js
Labels: back-development

#129 Aplicación para el móvil
  wichatApp/.gitignore
  wichatApp/App.js
  wichatApp/app.json
  wichatApp/assets/adaptive-icon.png
  wichatApp/assets/favicon.png
  wichatApp/assets/icon.png
  wichatApp/assets/splash.png
  wichatApp/babel.config.js
  wichatApp/eas.json
  wichatApp/package.json
Labels: front-development

#130 Añadido modo de juego de banderas
  questionservice/services/question-generate-service.js
  questionservice/utils/queryCategories.json
  webapp/public/images/gameMode/flag-gameMode.jpg
  webapp/src/pages/Game.js
  webapp/src/pages/GameMode.js
Labels: back-development

#128 Mejora de los datos mostrados al usuario.
  gatewayservice/gateway-service.js
  package-lock.json
  package.json
  users/authservice/auth-service.js
  users/historyservice/history-service.js
  users/historyservice/history-service.test.js
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  webapp/src/pages/History.js
Labels: front-development, back-development

#131 Añadido tests WebApp
  webapp/e2e/features/login-form.feature
  webapp/e2e/features/play-game.feature
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/play-game.steps.js
  webapp/src/components/NavBar.js
  webapp/src/localize/en.json
  webapp/src/localize/es.json
  webapp/src/pages/Game-VS.js
  webapp/src/pages/Game.js
  webapp/src/pages/History.js
  webapp/src/pages/Home.js
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
  webapp/src/pages/UserHome.js
  webapp/src/tests/components/Chat.test.js
  webapp/src/tests/components/NavBar.test.js
  webapp/src/tests/pages/Game-VS.test.js
  webapp/src/tests/pages/Game.test.js
  webapp/src/tests/pages/GameFinished.test.js
  webapp/src/tests/pages/GameMode.test.js
  webapp/src/tests/pages/GameType.test.js
  webapp/src/tests/pages/History.test.js
  webapp/src/tests/pages/Home.test.js
  webapp/src/tests/pages/Login.test.js
  webapp/src/tests/pages/UserHome.test.js
Labels: testing, front-development

#133 Coverage on new code
  gatewayservice/gateway-service.test.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/App.js
  webapp/src/components/Footer.js
  webapp/src/components/NavBar.js
  webapp/src/localize/en.json
  webapp/src/localize/es.json
  webapp/src/tests/components/Chat.test.js
  webapp/src/tests/components/Footer.test.js
  webapp/src/tests/components/NavBar.test.js
Labels: testing

#145 Arreglado error al reiniciar el juego desde game-finished
  webapp/src/pages/Game.js
Labels: bug

#146 Mejorado el modo de juego VS
  questionservice/models/question-model.js
  questionservice/services/question-generate-service.js
  questionservice/utils/queryCategories.json
  users/historyservice/package.json
  webapp/src/components/Chat.js
  webapp/src/pages/Game-VS.js
  webapp/src/pages/GameMode.js
  webapp/src/tests/components/Chat.test.js
Labels: back-development

#147 Añadido sonido al juego
  webapp/public/sound/bg_sound.wav
  webapp/public/sound/choose.mp3
  webapp/public/sound/correct.mp3
  webapp/public/sound/fail.wav
  webapp/public/sound/hurry_sound.mp3
  webapp/public/sound/winning.mp3
  webapp/src/pages/Game-VS.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
Labels: enhancement

#148 Notfound page
  webapp/src/App.js
  webapp/src/localize/en.json
  webapp/src/localize/es.json
  webapp/src/pages/NotFound.js
Labels: front-development

#152 Nuevo modo de juego de famosos
  questionservice/services/question-data-service.js
  questionservice/services/question-generate-service.js
  questionservice/services/question-service.js
  questionservice/test/question-generate-service.test.js
  questionservice/test/question-service.test.js
  questionservice/utils/queryCategories.json
  webapp/public/images/gameMode/famous-gameMode.jpg
  webapp/src/localize/en.json
  webapp/src/pages/Game-VS.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/GameType.js
  webapp/src/pages/Home.js
  webapp/src/tests/pages/GameMode.test.js
Labels: front-development, back-development

#166 Mejora de la documentación.
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#168 Añadido botón de descarga apk
  webapp/src/components/Footer.js
  webapp/src/localize/en.json
  webapp/src/localize/es.json
Labels: front-development

#169 Arreglo fallo en la foto de perfil
  gatewayservice/README.md
  webapp/src/components/Footer.js
  webapp/src/pages/History.js
Labels: bug

#170 Doc03 actualizado
  docs/images/03_technicalContext.png
  docs/src/03_context_and_scope.adoc
Labels: documentation

#171 Doc11 actualizado
  docs/src/11_technical_risks.adoc
Labels: documentation

#172 Actualizado Doc09
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#173 Doc05-Actualizada
  docs/images/05_2_whitebox2.png
  docs/images/05_3_BlackBox_Question_Management.png
  docs/images/05_3_BlackBox_User_Management.png
  docs/images/05_whitebox2.png
  docs/src/05_building_block_view.adoc
Labels: documentation

#177 Arreglado errores en los play()
  webapp/src/pages/Game-VS.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/GameType.js
  webapp/src/pages/History.js
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
  webapp/src/pages/UserHome.js
Labels: bug

#174 Doc08 Revisado
  docs/images/08_domainModel.png
  docs/src/08_concepts.adoc
Labels: documentation

#180 Arreglado que no se ejecutaran los tests de history
  .github/workflows/build.yml
  .github/workflows/release.yml
  users/historyservice/history-service.test.js
Labels: bug

#181 Arreglo problemas menores del historial
  webapp/src/pages/History.js
Labels: bug

#183 Deploy FUNCIONANDO
  .github/workflows/release.yml
  webapp/e2e/test-environment-setup.js
  webapp/src/pages/History.js
Labels: realise

#184 Arreglo historial, internacinalización, y tests
  webapp/src/App.js
  webapp/src/components/NavBar.js
  webapp/src/localize/en.json
  webapp/src/localize/es.json
  webapp/src/pages/Game-VS.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/History.js
  webapp/src/pages/UserHome.js
  webapp/src/tests/components/NavBar.test.js
  webapp/src/tests/pages/GameMode.test.js
Labels: bug, internationalization
