Repository Arquisoft/wichat_es6c, pull requests merged in 2025-03, with the labels that each got.

#50 Chat llm
  llmservice/llm-service.js
  llmservice/package-lock.json
  llmservice/package.json
  webapp/src/App.js
  webapp/src/components/Chat.js
  webapp/src/pages/Game.js
Labels: enhancement, front-development, back-development

#57 Añadir juego de países con datos extraídos de Wikidata
  .gitignore
  docker-compose.yml
  gatewayservice/.gitignore
  gatewayservice/gateway-service.js
  llmservice/.gitignore
  questions/.dockerignore
  questions/.gitignore
  questions/Dockerfile
  questions/models/question-model.js
  questions/package-lock.json
  questions/package.json
  questions/services/question-data-service.js
  questions/services/question-generate-service.js
  questions/services/question-service.js
  users/.gitignore
  users/authservice/.gitignore
  users/userservice/.gitignore
  users/userservice/user-service.test.js
  webapp/.dockerignore
  webapp/.gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/public/background-quiz.jpg
  webapp/src/App.js
  webapp/src/components/Chat.js
  webapp/src/components/NavBar.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/Home.js
  webapp/src/pages/PrivateRoute.js
  webapp/src/pages/UserHome.js
Labels: front-development, back-development

#58 Arreglos del chat LLM
  .github/workflows/release.yml
  questions/package-lock.json
  webapp/src/App.js
  webapp/src/components/Chat.js
  webapp/src/pages/Game.js
Labels: front-development, back-development

#65 Segundo entegable
  .github/workflows/release.yml
  .gitignore
  docker-compose.yml
  gatewayservice/.gitignore
  gatewayservice/gateway-service.js
  llmservice/.gitignore
  llmservice/llm-service.js
  llmservice/package-lock.json
  llmservice/package.json
  package-lock.json
  questions/.dockerignore
  questions/.gitignore
  questions/Dockerfile
  questions/models/question-model.js
  questions/package-lock.json
  questions/package.json
  questions/services/question-data-service.js
  questions/services/question-generate-service.js
  questions/services/question-service.js
  users/.gitignore
  users/authservice/.gitignore
  users/authservice/auth-service.js
  users/authservice/package-lock.json
  users/userservice/.gitignore
  users/userservice/package-lock.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/.dockerignore
  webapp/.gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/public/background-quiz.jpg
  webapp/src/App.js
  webapp/src/SessionContext.js
  webapp/src/components/AddUser.js
  webapp/src/components/Chat.js
  webapp/src/components/Login.js
  webapp/src/components/NavBar.js
  webapp/src/index.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/Home.js
  webapp/src/pages/Login.js
  webapp/src/pages/PrivateRoute.js
  webapp/src/pages/Register.js
  webapp/src/pages/UserHome.js
  webapp/src/tests/pages/Login.test.js
  webapp/src/tests/pages/Register.test.js
Labels: realise

#69 Corrección de errores y tests
  gatewayservice/gateway-service.test.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  questions/services/Dockerfile
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/.gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.js
  webapp/src/pages/Game.js
  webapp/src/pages/Login.js
  webapp/src/tests/App.test.js
  webapp/src/tests/pages/Login.test.js
  webapp/src/tests/pages/Register.test.js
Labels: bug, testing

#76 Añadida puntuación y tiempo al final de la partida
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
Labels: front-development

#77 Fixing first release
  gatewayservice/gateway-service.test.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  questions/services/Dockerfile
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/.gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/public/background-quiz.jpg
  webapp/public/icon-app.ico
  webapp/public/images/gameMode/pais-gameMode.jpg
  webapp/public/index.html
  webapp/public/logo-app.png
  webapp/src/App.test.js
  webapp/src/components/Chat.js
  webapp/src/components/NavBar.js
  webapp/src/pages/Game.js
  webapp/src/pages/GameFinished.js
  webapp/src/pages/GameMode.js
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
  webapp/src/pages/UserHome.js
  webapp/src/tests/App.test.js
  webapp/src/tests/pages/Login.test.js
  webapp/src/tests/pages/Register.test.js
Labels: realise

#80 Arreglo fallo apiKey expuesta
  .github/workflows/release.yml
  .vscode/settings.json
  README.md
  docker-compose.yml
  llmservice/.dockerignore
  llmservice/.gitignore
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  llmservice/package-lock.json
  llmservice/package.json
  users/userservice/user-service.js
  webapp/Dockerfile
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Chat.js
  webapp/src/pages/Game.js
  webapp/src/pages/Home.js
  webapp/src/pages/Login.js
Labels: bug
