Repository Arquisoft/wichat_es6c, pull requests merged in 2025-02, with the labels that each got.

#19 Doc01
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#24 Doc08
  docs/src/08_concepts.adoc
Labels: documentation

#18 Doc02: "Architecture Constraints"
  docs/src/02_architecture_constraints.adoc
Labels: documentation

#22 Doc04
  docs/src/04_solution_strategy.adoc
Labels: documentation

#25 Doc03 System Scope and Context
  docs/images/03_businessContext.png
  docs/images/03_technicalContext.png
  docs/src/03_context_and_scope.adoc
Labels: documentation

#28 Doc06 Runtime View
  docs/images/06_history.png
  docs/images/06_login.png
  docs/images/06_play.png
  docs/images/06_register.png
  docs/images/06_userLlm.png
  docs/src/06_runtime_view.adoc
  docs/src_mermaidCode/06_historial.txt
  docs/src_mermaidCode/06_login.txt
  docs/src_mermaidCode/06_play.txt
  docs/src_mermaidCode/06_register.txt
  docs/src_mermaidCode/06_userLlm.txt
Labels: documentation

#30 Doc11 Risks and Technical Debts
  docs/src/11_technical_risks.adoc
Labels: documentation

#26 Doc 08 "Cross-cutting Concepts"
  docs/images/08_domainModel.png
  docs/src/08_concepts.adoc
  docs/src_mermaidCode/08_domainModel.txt
Labels: documentation

#31 Doc09 Architecture Decisions
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#27 Doc05
  docs/images/05_2_whitebox2.png
  docs/images/05_whitebox.jpg
  docs/src/05_building_block_view.adoc
Labels: documentation

#34 Doc 12 "Glossary"
  docs/src/12_glossary.adoc
  webapp/Dockerfile
Labels: documentation

#32 Doc 10 "Quality Requirements"
  docs/images/10_qualityTree.png
  docs/src/10_quality_requirements.adoc
  docs/src_mermaidCode/10_qualityTree.txt
Labels: documentation

#35 Primer entregable
  docs/images/03_businessContext.png
  docs/images/03_technicalContext.png
  docs/images/05_2_whitebox2.png
  docs/images/05_whitebox.jpg
  docs/images/06_history.png
  docs/images/06_login.png
  docs/images/06_play.png
  docs/images/06_register.png
  docs/images/06_userLlm.png
  docs/images/08_domainModel.png
  docs/images/10_qualityTree.png
  docs/images/DiagramaDocker_g.webp
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/05_building_block_view.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/09_architecture_decisions.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
  docs/src_mermaidCode/06_historial.txt
  docs/src_mermaidCode/06_login.txt
  docs/src_mermaidCode/06_play.txt
  docs/src_mermaidCode/06_register.txt
  docs/src_mermaidCode/06_userLlm.txt
  docs/src_mermaidCode/08_domainModel.txt
  docs/src_mermaidCode/10_qualityTree.txt
  llmservice/llm-service.js
  webapp/Dockerfile
Labels: documentation

#42 Registro de usuarios
  docs/src/01_introduction_and_goals.adoc
  gatewayservice/gateway-service.js
  users/userservice/user-model.js
  users/userservice/user-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/SessionContext.js
  webapp/src/components/AddUser.js
  webapp/src/index.js
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
  webapp/src/tests/pages/Login.test.js
  webapp/src/tests/pages/Register.test.js
Labels: front-development, back-development

#48 Homepage y Home
  package-lock.json
  users/userservice/package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/NavBar.js
  webapp/src/pages/Home.js
  webapp/src/pages/Login.js
  webapp/src/pages/PrivateRoute.js
  webapp/src/pages/Register.js
  webapp/src/pages/UserHome.js
Labels: front-development

#46 Login
  package-lock.json
  users/authservice/auth-service.js
  users/authservice/package-lock.json
  webapp/package.json
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
Labels: front-development, back-development
